Update the SDK version
saleor/saleor-app-search pull request #35
Opened 2023-01-12 13:14 UTC by krzysztofwolski

2023-01-12 13:56 UTC, lkostrowski reviewed
if it works, lets release new app-sdk and bump to @latest then

2023-01-13 20:45 UTC, lkostrowski requested changes

2023-01-13 20:45 UTC, lkostrowski commented on package.json
> +    "@saleor/app-sdk": "0.26.0-4",
lets set proper tag

2023-01-13 20:45 UTC, lkostrowski commented on package.json
> +    "next": "13.1.2",
probably you should also update eslint-config-next

2023-01-13 20:45 UTC, lkostrowski commented on saleor-app.ts
> +  case "cloud": {
remember to update deployment env

2023-01-13 20:45 UTC, lkostrowski commented on src/components/AlgoliaConfigurationCard.tsx
> -          "saleor-domain": domain!,
lets import header names from app-sdk

2023-01-16 15:33 UTC, krzysztofwolski commented
APL variable name updated to `saleor-cloud` in deploymed app

2023-01-16 15:51 UTC, lkostrowski approved these changes

2023-01-17 16:02 UTC, merged